"""
Unit tests for S4-33: Learner DNA profile quality review.

Covers each of the 5 checklist rules (pass + fail), the review_profile
aggregator, load_from_fixture, write_report_csv, and main().
"""

from __future__ import annotations

import csv
import json
import os
import sys
import types

import pytest

# ---------------------------------------------------------------------------
# Make the standalone script importable without package infrastructure
# ---------------------------------------------------------------------------
_SCRIPT_DIR = os.path.join(os.path.dirname(__file__), "..", "scripts")
sys.path.insert(0, os.path.abspath(_SCRIPT_DIR))

import review_dna_profiles as rdp  # noqa: E402


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

DPDP = "This profile is generated by AI and is not a clinical assessment. Data processed per DPDP Act 2023."


def _make_profile(
    *,
    pid: str = "p-001",
    uid: str = "u-001",
    text: str | None = None,
    badges: list[str] | None = None,
) -> dict:
    return {
        "id": pid,
        "user_id": uid,
        "profile_text": text if text is not None else f"You are a Pattern Thinker. {DPDP}",
        "badge_labels": badges if badges is not None else ["Pattern Thinker"],
    }


# ---------------------------------------------------------------------------
# Rule: no_clinical
# ---------------------------------------------------------------------------


class TestNoClinical:
    def test_pass_no_clinical_terms(self):
        result, detail = rdp.check_no_clinical(f"You are a visual learner. {DPDP}")
        assert result == "PASS"
        assert detail == ""

    def test_fail_iq_uppercase(self):
        result, detail = rdp.check_no_clinical(f"Your IQ is high. {DPDP}")
        assert result == "FAIL"
        assert "IQ" in detail or "iq" in detail.lower()

    def test_fail_clinical_word(self):
        result, detail = rdp.check_no_clinical(f"This is a clinical assessment. {DPDP}")
        assert result == "FAIL"
        assert "clinical" in detail.lower()

    def test_fail_disorder(self):
        result, detail = rdp.check_no_clinical(f"No disorder found. {DPDP}")
        assert result == "FAIL"
        assert "disorder" in detail.lower()

    def test_fail_eq_lowercase(self):
        result, detail = rdp.check_no_clinical(f"Your eq places you here. {DPDP}")
        assert result == "FAIL"

    def test_pass_eq_in_word_is_not_flagged_wrong(self):
        # "sequence" contains "eq" but not as a whole word — should NOT be flagged
        result, _detail = rdp.check_no_clinical(f"You learn best through sequence. {DPDP}")
        assert result == "PASS"


# ---------------------------------------------------------------------------
# Rule: no_raw_scores
# ---------------------------------------------------------------------------


class TestNoRawScores:
    def test_pass_no_raw_scores(self):
        result, detail = rdp.check_no_raw_scores(f"You are a strong learner. {DPDP}")
        assert result == "PASS"
        assert detail == ""

    def test_fail_score_colon_digit(self):
        result, detail = rdp.check_no_raw_scores(f"You achieved score: 87. {DPDP}")
        assert result == "FAIL"
        assert "score" in detail.lower()

    def test_fail_fraction_pattern(self):
        result, detail = rdp.check_no_raw_scores(f"You answered 8/10 questions correctly. {DPDP}")
        assert result == "FAIL"
        assert "8/10" in detail

    def test_pass_fraction_in_date_not_flagged(self):
        # Dates like "2026-09-03" don't match \d+/\d+ — confirm no false positive
        result, _detail = rdp.check_no_raw_scores(f"Updated on 2026-09-03. {DPDP}")
        assert result == "PASS"


# ---------------------------------------------------------------------------
# Rule: has_dpdp
# ---------------------------------------------------------------------------


class TestHasDpdp:
    def test_pass_dpdp_present(self):
        result, detail = rdp.check_has_dpdp(f"You are a learner. {DPDP}")
        assert result == "PASS"
        assert detail == ""

    def test_fail_dpdp_missing(self):
        result, detail = rdp.check_has_dpdp("You are a learner. No disclaimer here.")
        assert result == "FAIL"
        assert "DPDP Act 2023" in detail

    def test_fail_partial_dpdp(self):
        result, _detail = rdp.check_has_dpdp("Data processed per DPDP Act 2022.")
        assert result == "FAIL"


# ---------------------------------------------------------------------------
# Rule: encouraging_tone
# ---------------------------------------------------------------------------


class TestEncouragingTone:
    def test_pass_encouraging_text(self):
        result, detail = rdp.check_encouraging_tone(f"You thrive with visual content. {DPDP}")
        assert result == "PASS"
        assert detail == ""

    def test_fail_struggle(self):
        result, detail = rdp.check_encouraging_tone(f"You tend to struggle with focus. {DPDP}")
        assert result == "FAIL"
        assert "struggle" in detail.lower()

    def test_fail_weak(self):
        result, detail = rdp.check_encouraging_tone(f"Your recall is weak in this area. {DPDP}")
        assert result == "FAIL"
        assert "weak" in detail.lower()

    def test_fail_poor(self):
        result, detail = rdp.check_encouraging_tone(f"Your attention score is poor. {DPDP}")
        assert result == "FAIL"
        assert "poor" in detail.lower()


# ---------------------------------------------------------------------------
# Rule: plain_badge_labels
# ---------------------------------------------------------------------------


class TestPlainBadgeLabels:
    def test_pass_plain_labels(self):
        result, detail = rdp.check_plain_badge_labels(["Pattern Thinker", "Visual Learner"])
        assert result == "PASS"
        assert detail == ""

    def test_fail_colon_in_label(self):
        result, detail = rdp.check_plain_badge_labels(["Memory: High"])
        assert result == "FAIL"
        assert "Memory: High" in detail

    def test_pass_empty_badges(self):
        result, _detail = rdp.check_plain_badge_labels([])
        assert result == "PASS"

    def test_pass_none_badges(self):
        # review_profile handles None → [] before calling check_plain_badge_labels
        result, _detail = rdp.check_plain_badge_labels([])
        assert result == "PASS"


# ---------------------------------------------------------------------------
# Aggregator: review_profile
# ---------------------------------------------------------------------------


class TestReviewProfile:
    def test_all_pass(self):
        profile = _make_profile()
        rows = rdp.review_profile(profile)
        assert len(rows) == 5
        assert all(r["result"] == "PASS" for r in rows)

    def test_clinical_fail_propagates(self):
        profile = _make_profile(text=f"Your IQ is high. {DPDP}", badges=["Thinker"])
        rows = rdp.review_profile(profile)
        fails = [r for r in rows if r["result"] == "FAIL"]
        assert any(r["rule"] == "no_clinical" for r in fails)

    def test_missing_dpdp_fail(self):
        profile = _make_profile(text="You are a strong learner.")
        rows = rdp.review_profile(profile)
        fails = [r for r in rows if r["result"] == "FAIL"]
        assert any(r["rule"] == "has_dpdp" for r in fails)

    def test_profile_id_and_user_id_in_rows(self):
        profile = _make_profile(pid="test-id-999", uid="user-abc")
        rows = rdp.review_profile(profile)
        assert all(r["profile_id"] == "test-id-999" for r in rows)
        assert all(r["user_id"] == "user-abc" for r in rows)


# ---------------------------------------------------------------------------
# load_from_fixture
# ---------------------------------------------------------------------------


class TestLoadFromFixture:
    def test_loads_10_profiles_from_sample_fixture(self):
        fixture_path = os.path.join(
            os.path.dirname(__file__), "fixtures", "sample_dna_profiles.json"
        )
        profiles = rdp.load_from_fixture(fixture_path)
        assert len(profiles) == 10

    def test_fixture_has_5_pass_profiles(self):
        fixture_path = os.path.join(
            os.path.dirname(__file__), "fixtures", "sample_dna_profiles.json"
        )
        profiles = rdp.load_from_fixture(fixture_path)
        pass_profiles = [p for p in profiles if "fail" not in p["id"]]
        assert len(pass_profiles) == 5

    def test_fixture_has_5_fail_profiles(self):
        fixture_path = os.path.join(
            os.path.dirname(__file__), "fixtures", "sample_dna_profiles.json"
        )
        profiles = rdp.load_from_fixture(fixture_path)
        fail_profiles = [p for p in profiles if "fail" in p["id"]]
        assert len(fail_profiles) == 5

    def test_missing_file_exits_2(self):
        with pytest.raises(SystemExit) as exc:
            rdp.load_from_fixture("/no/such/path/profiles.json")
        assert exc.value.code == 2

    def test_invalid_json_exits_2(self, tmp_path):
        bad = tmp_path / "bad.json"
        bad.write_text("not json", encoding="utf-8")
        with pytest.raises(SystemExit) as exc:
            rdp.load_from_fixture(str(bad))
        assert exc.value.code == 2

    def test_non_list_json_exits_2(self, tmp_path):
        bad = tmp_path / "bad.json"
        bad.write_text('{"key": "value"}', encoding="utf-8")
        with pytest.raises(SystemExit) as exc:
            rdp.load_from_fixture(str(bad))
        assert exc.value.code == 2


# ---------------------------------------------------------------------------
# write_report_csv
# ---------------------------------------------------------------------------


class TestWriteReportCsv:
    def test_csv_has_correct_headers(self, tmp_path):
        out = str(tmp_path / "report.csv")
        rows = [{"profile_id": "p1", "user_id": "u1", "rule": "has_dpdp", "result": "PASS", "detail": ""}]
        rdp.write_report_csv(rows, out)
        with open(out, encoding="utf-8") as f:
            reader = csv.DictReader(f)
            assert set(reader.fieldnames or []) == {"profile_id", "user_id", "rule", "result", "detail"}

    def test_csv_row_count_matches_input(self, tmp_path):
        out = str(tmp_path / "report.csv")
        rows = [
            {"profile_id": f"p{i}", "user_id": "u1", "rule": "no_clinical", "result": "PASS", "detail": ""}
            for i in range(7)
        ]
        rdp.write_report_csv(rows, out)
        with open(out, encoding="utf-8") as f:
            reader = csv.DictReader(f)
            assert len(list(reader)) == 7


# ---------------------------------------------------------------------------
# main() integration
# ---------------------------------------------------------------------------


class TestMain:
    def test_main_returns_0_all_pass(self, tmp_path):
        profiles = [_make_profile(pid=f"p{i}", uid=f"u{i}") for i in range(3)]
        fixture = tmp_path / "profiles.json"
        fixture.write_text(json.dumps(profiles), encoding="utf-8")
        out = str(tmp_path / "report.csv")
        rc = rdp.main(["--fixture", str(fixture), "--output", out])
        assert rc == 0

    def test_main_returns_1_with_fail(self, tmp_path):
        profiles = [_make_profile(pid="p1", text=f"Your IQ is high. {DPDP}")]
        fixture = tmp_path / "profiles.json"
        fixture.write_text(json.dumps(profiles), encoding="utf-8")
        out = str(tmp_path / "report.csv")
        rc = rdp.main(["--fixture", str(fixture), "--output", out])
        assert rc == 1

    def test_main_returns_2_no_input(self, monkeypatch):
        monkeypatch.delenv("SUPABASE_URL", raising=False)
        monkeypatch.delenv("SUPABASE_SERVICE_ROLE_KEY", raising=False)
        rc = rdp.main([])
        assert rc == 2

    def test_main_produces_csv_file(self, tmp_path):
        profiles = [_make_profile()]
        fixture = tmp_path / "profiles.json"
        fixture.write_text(json.dumps(profiles), encoding="utf-8")
        out = str(tmp_path / "report.csv")
        rdp.main(["--fixture", str(fixture), "--output", out])
        assert os.path.exists(out)

    def test_main_csv_has_50_rows_for_10_profiles_5_rules(self, tmp_path):
        fixture_path = os.path.join(
            os.path.dirname(__file__), "fixtures", "sample_dna_profiles.json"
        )
        out = str(tmp_path / "report.csv")
        rdp.main(["--fixture", fixture_path, "--output", out])
        with open(out, encoding="utf-8") as f:
            reader = csv.DictReader(f)
            rows = list(reader)
        assert len(rows) == 50  # 10 profiles × 5 rules

    def test_fixture_5_fail_profiles_produce_exactly_5_fail_rows(self, tmp_path):
        fixture_path = os.path.join(
            os.path.dirname(__file__), "fixtures", "sample_dna_profiles.json"
        )
        out = str(tmp_path / "report.csv")
        rdp.main(["--fixture", fixture_path, "--output", out])
        with open(out, encoding="utf-8") as f:
            reader = csv.DictReader(f)
            rows = list(reader)
        fail_rows = [r for r in rows if r["result"] == "FAIL"]
        assert len(fail_rows) == 5  # exactly one FAIL per violation profile
