"""Diagnose why a generated lesson is shorter than its requested duration.

READ-ONLY. Touches exactly one lesson: one `lessons` row and one `lesson_jobs`
row, both fetched by primary key. No writes, no scans.

    SUPABASE_URL=https://... SUPABASE_SERVICE_KEY=... \
        python scripts/diagnose_lesson_duration.py <lesson_id>

Answers, from the stored record rather than from arithmetic:

  1. Is this UUID actually a lesson_id (vs. a session/chapter id)?
  2. What does its lesson_jobs row hold?
  3. section_truncations — did the per-section Phase-1 window (45,000) bite?
  4. duration_report — present only for lessons generated by Story S5-4 code.
  5. How many sections did the chapter yield, before and after coalescing?
  6. How much of the chapter's text was actually visible to the generator?
  7. Section detection vs. the source window — which one bounded the lesson?
  8. Requested duration vs. the content the generator could actually see.

It also checks the causes that are NOT about truncation at all — dropped or
degraded segments, cost-ceiling downshifts, TTS fallbacks — so a short lesson
is not blamed on the window when something else produced it.
"""

from __future__ import annotations

import json
import os
import sys
from typing import Any

from supabase import create_client  # type: ignore[import]

# The slice size comes from the implementation itself, not a retyped copy: a
# mirrored constant here is how this script came to report a 6,000-char window
# for months after Story 233 made it 45,000. segment_expansion is pure (no
# settings, no I/O), so importing it needs no environment.
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "apps", "api"))
try:
    from app.modules.content.pipeline.nodes.segment_expansion import (  # noqa: E402
        CHARS_PER_WORD as _IMPL_CHARS_PER_WORD,
    )
    from app.modules.content.pipeline.nodes.segment_expansion import (  # noqa: E402
        unit_slice_chars as _impl_unit_slice_chars,
    )
except ImportError:  # run from a checkout without apps/api -- fall back, and say so
    _IMPL_CHARS_PER_WORD = None
    _impl_unit_slice_chars = None

# Mirrors app.config defaults. Printed with every derived number so a stale
# assumption here is visible rather than silently load-bearing.
# Story 233 (d38d884) raised this from 6,000 to 45,000 when topic_selection
# began collapsing a chapter into 1-2 large topics. This script kept the old
# 6,000 and therefore reported a 'visible / discarded' split, and a 'hard
# ceiling', that the pipeline has not applied since Story 233 merged.
SECTION_BODY_MAX_CHARS = 45_000
STRUCTURE_MAX_SECTIONS = 15
STRUCTURE_MIN_SECTION_CHARS = 200
WORDS_PER_MINUTE = 150
SARVAM_PACE = 0.85
CHARS_PER_WORD = _IMPL_CHARS_PER_WORD or 6.0
NARRATION_WORDS_PER_SEGMENT = 900  # mirrors settings.narration_words_per_segment
TIER_SEAT_MINUTES = {"T1": 45, "T2": 30, "T3": 15}
# S5-5/D192: the tier figure is the MINIMUM NARRATION duration, not 65% of
# a seat-time budget. 45 means 45 minutes of speech.
NARRATION_SHARE = 1.0


def _eff_wpm(node_outputs: dict) -> tuple[float, str]:
    """Effective narration WPM, preferring what the pipeline actually used.

    segment_expansion records it directly (S5-5). Failing that it is
    recoverable from duration_report.capacity_min, which is
    total_source_chars / CHARS_PER_WORD / effective_wpm. Only if neither is
    present do we guess -- and we say so, because 150 (60db, pace 1.0) and
    127.5 (Sarvam, pace 0.85) differ by 18%.
    """
    exp = node_outputs.get("segment_expansion")
    if isinstance(exp, dict) and exp.get("effective_wpm"):
        return float(exp["effective_wpm"]), "recorded by segment_expansion"
    rep_ = node_outputs.get("duration_report")
    struct = node_outputs.get("structure") or {}
    secs = (struct.get("sections") if isinstance(struct, dict) else None) or []
    total = sum(len((x or {}).get("body") or "") for x in secs if isinstance(x, dict))
    if isinstance(rep_, dict) and rep_.get("capacity_min") and total:
        derived = (total / CHARS_PER_WORD) / float(rep_["capacity_min"])
        return derived, "derived from duration_report.capacity_min"
    return WORDS_PER_MINUTE * SARVAM_PACE, "ASSUMED (Sarvam) -- not from the record"


def _unit_slice_chars() -> tuple[int, str]:
    """The per-unit slice size, derived exactly as segment_expansion_node does."""
    if _impl_unit_slice_chars is not None:
        return (
            _impl_unit_slice_chars(
                words_per_segment=NARRATION_WORDS_PER_SEGMENT, window_chars=SECTION_BODY_MAX_CHARS
            ),
            "segment_expansion.unit_slice_chars",
        )
    return (
        min(int(NARRATION_WORDS_PER_SEGMENT * CHARS_PER_WORD), SECTION_BODY_MAX_CHARS),
        "FALLBACK formula -- apps/api not importable",
    )


def _expansion_was_a_noop(node_outputs: dict) -> bool:
    """True when segment_expansion allocated more units than it emitted."""
    exp = node_outputs.get("segment_expansion")
    if not isinstance(exp, dict):
        return False
    planned = sum(exp.get("per_topic_segments") or [])
    produced = exp.get("segment_count") or 0
    return bool(planned and produced and planned > produced)


def _h(title: str) -> None:
    print(f"\n{'=' * 78}\n{title}\n{'=' * 78}")


def _get(d: Any, *path: str, default: Any = None) -> Any:
    cur = d
    for key in path:
        if not isinstance(cur, dict):
            return default
        cur = cur.get(key)
        if cur is None:
            return default
    return cur


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit("usage: python scripts/diagnose_lesson_duration.py <lesson_id>")
    lesson_id = sys.argv[1].strip()

    url = os.environ.get("SUPABASE_URL")
    key = os.environ.get("SUPABASE_SERVICE_KEY")
    if not url or not key:
        sys.exit("Error: SUPABASE_URL and SUPABASE_SERVICE_KEY must be set.")
    sb = create_client(url, key)

    # ── Q1: is this really a lesson_id? ──────────────────────────────────────
    _h("Q1 — is this UUID a lesson_id?")
    lesson_resp = (
        sb.table("lessons")
        .select("lesson_id,user_id,book_id,chapter_id,tier,status,created_at,content")
        .eq("lesson_id", lesson_id)
        .limit(1)
        .execute()
    )
    lesson_rows = lesson_resp.data or []
    if not lesson_rows:
        print(f"  NO `lessons` row for {lesson_id}.")
        for table, col in (("sessions", "session_id"), ("chapters", "chapter_id")):
            try:
                alt = sb.table(table).select(col).eq(col, lesson_id).limit(1).execute()
                if alt.data:
                    print(f"  -> it IS a {col} in `{table}`. Re-run with the real lesson_id.")
            except Exception as exc:  # noqa: BLE001 — probe only; table may not exist
                print(f"     (probe of `{table}` skipped: {type(exc).__name__})")
        sys.exit(1)

    lesson = lesson_rows[0]
    tier = lesson.get("tier") or "?"
    seat = TIER_SEAT_MINUTES.get(tier)
    print(f"  CONFIRMED lesson_id={lesson_id}")
    print(f"  tier={tier}" + (f"  (advertised {seat} min seat time)" if seat else ""))
    print(f"  status={lesson.get('status')}  created_at={lesson.get('created_at')}")
    print(f"  book_id={lesson.get('book_id')}  chapter_id={lesson.get('chapter_id')}")

    # ── Q2: the lesson_jobs record ───────────────────────────────────────────
    _h("Q2 — lesson_jobs record")
    jobs_resp = (
        sb.table("lesson_jobs")
        .select("lesson_id,status,last_node,error,node_outputs,created_at,completed_at")
        .eq("lesson_id", lesson_id)
        .limit(1)
        .execute()
    )
    jobs = (jobs_resp.data or [{}])[0]
    if not jobs:
        sys.exit("  NO lesson_jobs row — cannot diagnose generation without it.")
    node_outputs: dict[str, Any] = jobs.get("node_outputs") or {}
    print(f"  status={jobs.get('status')}  last_node={jobs.get('last_node')}")
    print(f"  error={jobs.get('error')}")
    print(f"  nodes recorded: {', '.join(sorted(node_outputs.keys())) or '(none)'}")

    # ── Q5: section counts, before and after coalescing ──────────────────────
    _h("Q5 — how many sections did the chapter yield?")
    structure = node_outputs.get("structure") or node_outputs.get("structure_detect") or {}
    sections = (structure.get("sections") if isinstance(structure, dict) else None) or []
    raw_count = _get(structure, "raw_section_count", default=None)
    body_lengths = [len((s or {}).get("body") or "") for s in sections if isinstance(s, dict)]

    if not sections:
        print("  structure node output holds no section bodies in node_outputs.")
        print("  Falling back to the shipped package's segment count.")
    print(
        f"  sections AFTER coalescing: {len(sections) or '(unknown)'}"
        f"   (cap = {STRUCTURE_MAX_SECTIONS}, min-body floor = {STRUCTURE_MIN_SECTION_CHARS})"
    )
    if raw_count is not None:
        print(f"  sections BEFORE coalescing: {raw_count}")
    else:
        print("  sections BEFORE coalescing: not recorded by structure_node")
    if body_lengths:
        print(
            f"  body lengths: min={min(body_lengths):,}  max={max(body_lengths):,}  "
            f"total={sum(body_lengths):,} chars"
        )

    # ── Q3 + Q6: truncation, and how much text was visible ───────────────────
    _h(f"Q3/Q6 — did the {SECTION_BODY_MAX_CHARS:,}-char per-section window truncate this chapter?")
    truncations = node_outputs.get("section_truncations") or []
    print(f"  section_truncations entries: {len(truncations)}")
    if truncations:
        shown = 0
        for t in truncations:
            if not isinstance(t, dict):
                continue
            print(
                f"    - node={t.get('node')} section={t.get('section_id')} "
                f"original={t.get('original_chars')} kept={t.get('kept_chars')}"
            )
            shown += 1
            if shown >= 12:
                print(f"    ... and {len(truncations) - shown} more")
                break
    else:
        print("  NONE recorded — the per-section window did NOT bite for this lesson.")
        print("  (If so, the short lesson has a different cause; see Q7 below.)")

    if body_lengths:
        total_chars = sum(body_lengths)
        visible = sum(min(b, SECTION_BODY_MAX_CHARS) for b in body_lengths)
        eff_wpm, _wpm_src = _eff_wpm(node_outputs)
        print(f"\n  chapter text total : {total_chars:,} chars")
        print(
            f"  LLM-visible        : {visible:,} chars  ({visible / total_chars:.0%} of the chapter)"
            if total_chars
            else ""
        )
        print(f"  discarded silently : {total_chars - visible:,} chars")
        print(f"  max narration from visible text: {(visible / CHARS_PER_WORD) / eff_wpm:.1f} min")

    # ── Q4: duration_report (S5-4 only) ──────────────────────────────────────
    _h("Q4 — duration_report (present only on Story S5-4 code)")
    report = node_outputs.get("duration_report")
    if report:
        print(json.dumps(report, indent=2)[:2500])
    else:
        print("  ABSENT — this lesson was generated before S5-4 merged.")
        print("  Meaning: NO duration budget was enforced at generation time. The")
        print("  tier was a label only; narration had no length target at all.")

    # ── Q7: the causes that are NOT the window ───────────────────────────────
    _h("Q7 — other causes of a short lesson (ruled in or out)")
    degraded = node_outputs.get("package_builder_degraded") or {}
    print(f"  segments shipped        : {degraded.get('total_segments', '?')}")
    print(f"  segments degraded       : {len(degraded.get('segment_ids') or [])}")
    print(f"  segments DROPPED        : {len(degraded.get('dropped_segment_ids') or [])}")
    downshifts = [k for k in node_outputs if "downshift" in k.lower()]
    print(f"  cost-ceiling downshifts : {downshifts or 'none recorded'}")

    pkg = lesson.get("content") or node_outputs.get("package_builder") or {}
    segs = (pkg or {}).get("segments") or []
    if segs:
        words, providers = 0, {}
        for s in segs:
            narr = s.get("narration") or {}
            script = narr.get("script") or ""
            words += len(script.split())
            for a in (narr.get("audio_provider"),):
                if a:
                    providers[a] = providers.get(a, 0) + 1
        eff_wpm, _wpm_src = _eff_wpm(node_outputs)
        print(f"\n  SHIPPED PACKAGE: {len(segs)} segments, {words:,} narration words")
        print(
            f"  implied narration time: {words / eff_wpm:.1f} min (at {eff_wpm:.1f} effective wpm)"
        )
        print(
            f"  metadata.estimated_duration_mins: "
            f"{_get(pkg, 'metadata', 'estimated_duration_mins', default='?')}"
        )
        print(f"  audio providers used: {providers or '(not recorded per segment)'}")
        quiz_total = sum(len(s.get("quiz") or []) for s in segs)
        print(f"  quiz questions shipped: {quiz_total}")

    # ── Q8: requested vs. deliverable ────────────────────────────────────────
    _h("Q8 — requested duration vs. what the source could support")
    if seat:
        target_narration = seat * NARRATION_SHARE
        eff_wpm, _wpm_src = _eff_wpm(node_outputs)
        need_chars = target_narration * eff_wpm * CHARS_PER_WORD
        print(f"  requested            : {seat} min seat time (tier {tier})")
        print(
            f"  narration target     : {target_narration:.2f} min "
            f"(= the tier MINIMUM narration under S5-5/D192)"
        )
        print(f"  source chars needed  : ~{need_chars:,.0f}")
        if body_lengths:
            visible = sum(min(b, SECTION_BODY_MAX_CHARS) for b in body_lengths)
            print(f"  source chars visible : {visible:,}")
            print(
                f"  shortfall            : {max(0, need_chars - visible):,.0f} chars "
                f"({visible / need_chars:.0%} of what the target needs)"
            )
            ceiling = len(body_lengths) * SECTION_BODY_MAX_CHARS
            print(
                f"\n  HARD CEILING for this chapter's section count "
                f"({len(body_lengths)} x {SECTION_BODY_MAX_CHARS:,}) = {ceiling:,} chars "
                f"= {(ceiling / CHARS_PER_WORD) / eff_wpm:.1f} min of narration"
            )
    else:
        print(f"  tier {tier!r} not in the seat-time table — cannot compare.")

    # ── PIPELINE FLOW: where did the units actually come from? ──────────────
    _h("PIPELINE FLOW — structure -> topic_selection -> segment_expansion -> Phase 1")
    _wpm, _src = _eff_wpm(node_outputs)
    _slice, _slice_src = _unit_slice_chars()
    print(f"  effective_wpm used: {_wpm:.1f}  ({_src})")
    print(f"  Phase-1 window    : {SECTION_BODY_MAX_CHARS:,} chars (section_body_max_chars)")
    print(f"  unit slice size   : {_slice:,} chars ({_slice_src})")

    def _stage(name: str, node: Any) -> list[int]:
        secs = node.get("sections") if isinstance(node, dict) else None
        if not isinstance(secs, list):
            return []
        return [len((x or {}).get("body") or "") for x in secs if isinstance(x, dict)]

    for label, key in (("structure", "structure"), ("topic_selection", "topic_selection")):
        lens = _stage(label, node_outputs.get(key) or {})
        if lens:
            print(f"  {label:<17}: {len(lens)} unit(s)  total={sum(lens):,} chars  lengths={lens}")
        else:
            print(f"  {label:<17}: not recorded with bodies")

    exp = node_outputs.get("segment_expansion")
    if not isinstance(exp, dict):
        print("  segment_expansion : ABSENT — lesson predates Story S5-5")
    else:
        unit_lens = _stage("segment_expansion", exp)
        planned = exp.get("per_topic_segments") or []
        produced = len(unit_lens) or exp.get("segment_count") or 0
        print(f"  segment_expansion : expanded={exp.get('expanded')}  "
              f"topics={exp.get('topic_count')} -> units={exp.get('segment_count')}")
        for field in ("per_topic_segments", "requested_min_minutes", "achievable_minutes",
                      "content_limited", "capped_by_max_segments", "cap_overrun",
                      "max_segments_configured", "effective_wpm",
                      "unit_slice_chars", "untaught_chars_per_topic"):
            if field in exp:
                print(f"      {field:<24}: {exp[field]}")
        if unit_lens:
            print(f"      UNIT BODY LENGTHS       : {unit_lens}  total={sum(unit_lens):,}")
            print(f"      largest unit vs window  : {max(unit_lens):,} vs "
                  f"{SECTION_BODY_MAX_CHARS:,} (section_body_max_chars)")
        want = sum(planned) if planned else 0
        if want and produced and want != produced:
            print("")
            print(f"      *** PLAN/OUTPUT MISMATCH: the plan allocated {want} unit(s) "
                  f"but only {produced} were produced.")
            if "unit_slice_chars" not in exp:
                print("      *** No unit_slice_chars in the record: generated before the D195 "
                      "fix, when the node passed the Phase-1 window as the slice size and "
                      "every topic under it came back whole.")
            else:
                print("      *** unit_slice_chars IS recorded, so this is post-D195 -- a NEW "
                      "defect, not the inert-expansion one.")
        untaught = exp.get("untaught_chars_per_topic")
        if isinstance(untaught, list) and any(untaught):
            print(f"      untaught source (D194): {sum(untaught):,} chars across topics "
                  f"{untaught} -- the tier needed less than the chapter holds.")

    phase1 = {}
    for k in node_outputs:
        if ":" in k:
            phase1[k.split(":", 1)[0]] = phase1.get(k.split(":", 1)[0], 0) + 1
    if phase1:
        print("  Phase-1 dispatches: " + ", ".join(f"{k} x{v}" for k, v in sorted(phase1.items())))

    _h("PER-SEGMENT TABLE (for the T3/T2/T1 comparison)")
    if segs:
        eff, _ = _eff_wpm(node_outputs)
        dur_by_id = {}
        # tts_node's checkpoint is a LIST of audio assets in production; an
        # earlier shape wrapped them in {'audio_assets': [...]}. Accept both,
        # and anything else without crashing the whole diagnostic.
        _tts = node_outputs.get("tts_node")
        if isinstance(_tts, dict):
            _assets = _tts.get("audio_assets") or []
        elif isinstance(_tts, list):
            _assets = _tts
        else:
            _assets = []
        for item in _assets:
            if isinstance(item, dict):
                dur_by_id[item.get("segment_id")] = item.get("duration_ms")
        print(f"  {'#':>2} {'segment_id':<34} {'words':>6} {'narr min':>9} {'quiz':>5}")
        total_w = total_q = 0
        for i, sg in enumerate(segs):
            sid = str(sg.get("segment_id", ""))[:34]
            w = len(((sg.get("narration") or {}).get("script") or "").split())
            q = len(sg.get("quiz") or [])
            total_w += w
            total_q += q
            print(f"  {i:>2} {sid:<34} {w:>6,} {w / eff:>8.2f}m {q:>5}")
        print(f"  {'':>2} {'TOTAL':<34} {total_w:>6,} {total_w / eff:>8.2f}m {total_q:>5}")
        rep = node_outputs.get("duration_report") or {}
        exp = node_outputs.get("segment_expansion") or {}
        print("")
        print(
            f"  segment_count={len(segs)}  "
            f"measured_narration_min={rep.get('measured_narration_min')}  "
            f"content_limited={rep.get('content_limited')}"
        )
        if exp:
            print(
                f"  segment_expansion: topics={exp.get('topic_count')} -> "
                f"units={exp.get('segment_count')}  per_topic={exp.get('per_topic_segments')}  "
                f"requested_min={exp.get('requested_min_minutes')}  "
                f"achievable={exp.get('achievable_minutes')}  "
                f"capped={exp.get('capped_by_max_segments')}  "
                f"cap_overrun={exp.get('cap_overrun', 0)}"
                f"/{exp.get('max_segments_configured', '?')}"
            )
        else:
            print("  segment_expansion: ABSENT (lesson predates Story S5-5)")

    _h("VERDICT")
    if truncations and body_lengths:
        n = len(body_lengths)
        print(
            f"  The per-section {SECTION_BODY_MAX_CHARS:,}-char window truncated "
            f"{len(truncations)} call(s)."
        )
        print(
            f"  With {n} section(s), the chapter can never exceed "
            f"{(n * SECTION_BODY_MAX_CHARS / CHARS_PER_WORD) / _eff_wpm(node_outputs)[0]:.1f} "
            f"min of narration, whatever duration is requested."
        )
        print("  -> Root cause is the SOURCE WINDOW, bounded by the section count.")
    elif _expansion_was_a_noop(node_outputs):
        exp = node_outputs["segment_expansion"]
        print(
            f"  segment_expansion planned {sum(exp.get('per_topic_segments') or [])} "
            f"unit(s) but produced {exp.get('segment_count')}."
        )
        if "unit_slice_chars" not in exp:
            print(
                "  Generated before the D195 fix: the node passed the Phase-1 window "
                f"({SECTION_BODY_MAX_CHARS:,}) as the slice size, so every topic under it "
                "came back whole."
            )
            print("  -> Root cause is SEGMENT EXPANSION being inert (D195), not the source length.")
        else:
            print("  unit_slice_chars is recorded -- post-D195. This is a NEW mismatch.")
            print("  -> Investigate segment_expansion_node; D195's guard tests should have caught it.")
    elif body_lengths and len(body_lengths) <= 3:
        print("  No truncation recorded, but the chapter yielded very few sections.")
        print("  -> Look at SECTION DETECTION first.")
    else:
        print("  Neither truncation nor a low section count explains it.")
        print("  -> Look at Q7: dropped/degraded segments, or generation-time failure.")


if __name__ == "__main__":
    main()
