"""Diagnose why a generated lesson is shorter than its requested duration.

READ-ONLY. Touches exactly one lesson: one `lessons` row and one `lesson_jobs`
row, both fetched by primary key. No writes, no scans.

    SUPABASE_URL=https://... SUPABASE_SERVICE_KEY=... \
        python scripts/diagnose_lesson_duration.py <lesson_id>

Answers, from the stored record rather than from arithmetic:

  1. Is this UUID actually a lesson_id (vs. a session/chapter id)?
  2. What does its lesson_jobs row hold?
  3. section_truncations — did the 6,000-char per-section window bite?
  4. duration_report — present only for lessons generated by Story S5-4 code.
  5. How many sections did the chapter yield, before and after coalescing?
  6. How much of the chapter's text was actually visible to the generator?
  7. Section detection vs. the source window — which one bounded the lesson?
  8. Requested duration vs. the content the generator could actually see.

It also checks the causes that are NOT about truncation at all — dropped or
degraded segments, cost-ceiling downshifts, TTS fallbacks — so a short lesson
is not blamed on the window when something else produced it.
"""

from __future__ import annotations

import json
import os
import sys
from typing import Any

from supabase import create_client  # type: ignore[import]

# Mirrors app.config defaults. Printed with every derived number so a stale
# assumption here is visible rather than silently load-bearing.
SECTION_BODY_MAX_CHARS = 6000
STRUCTURE_MAX_SECTIONS = 15
STRUCTURE_MIN_SECTION_CHARS = 200
WORDS_PER_MINUTE = 150
SARVAM_PACE = 0.85
CHARS_PER_WORD = 6.0
TIER_SEAT_MINUTES = {"T1": 45, "T2": 30, "T3": 15}
NARRATION_SHARE = 0.65


def _h(title: str) -> None:
    print(f"\n{'=' * 78}\n{title}\n{'=' * 78}")


def _get(d: Any, *path: str, default: Any = None) -> Any:
    cur = d
    for key in path:
        if not isinstance(cur, dict):
            return default
        cur = cur.get(key)
        if cur is None:
            return default
    return cur


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit("usage: python scripts/diagnose_lesson_duration.py <lesson_id>")
    lesson_id = sys.argv[1].strip()

    url = os.environ.get("SUPABASE_URL")
    key = os.environ.get("SUPABASE_SERVICE_KEY")
    if not url or not key:
        sys.exit("Error: SUPABASE_URL and SUPABASE_SERVICE_KEY must be set.")
    sb = create_client(url, key)

    # ── Q1: is this really a lesson_id? ──────────────────────────────────────
    _h("Q1 — is this UUID a lesson_id?")
    lesson_resp = (
        sb.table("lessons")
        .select("lesson_id,user_id,book_id,chapter_id,tier,status,created_at,content")
        .eq("lesson_id", lesson_id)
        .limit(1)
        .execute()
    )
    lesson_rows = lesson_resp.data or []
    if not lesson_rows:
        print(f"  NO `lessons` row for {lesson_id}.")
        for table, col in (("sessions", "session_id"), ("chapters", "chapter_id")):
            try:
                alt = sb.table(table).select(col).eq(col, lesson_id).limit(1).execute()
                if alt.data:
                    print(
                        f"  -> it IS a {col} in `{table}`. Re-run with the real lesson_id."
                    )
            except Exception as exc:  # noqa: BLE001 — probe only; table may not exist
                print(f"     (probe of `{table}` skipped: {type(exc).__name__})")
        sys.exit(1)

    lesson = lesson_rows[0]
    tier = lesson.get("tier") or "?"
    seat = TIER_SEAT_MINUTES.get(tier)
    print(f"  CONFIRMED lesson_id={lesson_id}")
    print(f"  tier={tier}" + (f"  (advertised {seat} min seat time)" if seat else ""))
    print(f"  status={lesson.get('status')}  created_at={lesson.get('created_at')}")
    print(f"  book_id={lesson.get('book_id')}  chapter_id={lesson.get('chapter_id')}")

    # ── Q2: the lesson_jobs record ───────────────────────────────────────────
    _h("Q2 — lesson_jobs record")
    jobs_resp = (
        sb.table("lesson_jobs")
        .select("lesson_id,status,last_node,error,node_outputs,created_at,completed_at")
        .eq("lesson_id", lesson_id)
        .limit(1)
        .execute()
    )
    jobs = (jobs_resp.data or [{}])[0]
    if not jobs:
        sys.exit("  NO lesson_jobs row — cannot diagnose generation without it.")
    node_outputs: dict[str, Any] = jobs.get("node_outputs") or {}
    print(f"  status={jobs.get('status')}  last_node={jobs.get('last_node')}")
    print(f"  error={jobs.get('error')}")
    print(f"  nodes recorded: {', '.join(sorted(node_outputs.keys())) or '(none)'}")

    # ── Q5: section counts, before and after coalescing ──────────────────────
    _h("Q5 — how many sections did the chapter yield?")
    structure = (
        node_outputs.get("structure") or node_outputs.get("structure_detect") or {}
    )
    sections = (
        structure.get("sections") if isinstance(structure, dict) else None
    ) or []
    raw_count = _get(structure, "raw_section_count", default=None)
    body_lengths = [
        len((s or {}).get("body") or "") for s in sections if isinstance(s, dict)
    ]

    if not sections:
        print("  structure node output holds no section bodies in node_outputs.")
        print("  Falling back to the shipped package's segment count.")
    print(
        f"  sections AFTER coalescing: {len(sections) or '(unknown)'}"
        f"   (cap = {STRUCTURE_MAX_SECTIONS}, min-body floor = {STRUCTURE_MIN_SECTION_CHARS})"
    )
    if raw_count is not None:
        print(f"  sections BEFORE coalescing: {raw_count}")
    else:
        print("  sections BEFORE coalescing: not recorded by structure_node")
    if body_lengths:
        print(
            f"  body lengths: min={min(body_lengths):,}  max={max(body_lengths):,}  "
            f"total={sum(body_lengths):,} chars"
        )

    # ── Q3 + Q6: truncation, and how much text was visible ───────────────────
    _h("Q3/Q6 — did the 6,000-char per-section window truncate this chapter?")
    truncations = node_outputs.get("section_truncations") or []
    print(f"  section_truncations entries: {len(truncations)}")
    if truncations:
        shown = 0
        for t in truncations:
            if not isinstance(t, dict):
                continue
            print(
                f"    - node={t.get('node')} section={t.get('section_id')} "
                f"original={t.get('original_chars')} kept={t.get('kept_chars')}"
            )
            shown += 1
            if shown >= 12:
                print(f"    ... and {len(truncations) - shown} more")
                break
    else:
        print("  NONE recorded — the per-section window did NOT bite for this lesson.")
        print("  (If so, the short lesson has a different cause; see Q7 below.)")

    if body_lengths:
        total_chars = sum(body_lengths)
        visible = sum(min(b, SECTION_BODY_MAX_CHARS) for b in body_lengths)
        eff_wpm = WORDS_PER_MINUTE * SARVAM_PACE
        print(f"\n  chapter text total : {total_chars:,} chars")
        print(
            f"  LLM-visible        : {visible:,} chars  ({visible / total_chars:.0%} of the chapter)"
            if total_chars
            else ""
        )
        print(f"  discarded silently : {total_chars - visible:,} chars")
        print(
            f"  max narration from visible text: "
            f"{(visible / CHARS_PER_WORD) / eff_wpm:.1f} min"
        )

    # ── Q4: duration_report (S5-4 only) ──────────────────────────────────────
    _h("Q4 — duration_report (present only on Story S5-4 code)")
    report = node_outputs.get("duration_report")
    if report:
        print(json.dumps(report, indent=2)[:2500])
    else:
        print("  ABSENT — this lesson was generated before S5-4 merged.")
        print("  Meaning: NO duration budget was enforced at generation time. The")
        print("  tier was a label only; narration had no length target at all.")

    # ── Q7: the causes that are NOT the window ───────────────────────────────
    _h("Q7 — other causes of a short lesson (ruled in or out)")
    degraded = node_outputs.get("package_builder_degraded") or {}
    print(f"  segments shipped        : {degraded.get('total_segments', '?')}")
    print(f"  segments degraded       : {len(degraded.get('segment_ids') or [])}")
    print(
        f"  segments DROPPED        : {len(degraded.get('dropped_segment_ids') or [])}"
    )
    downshifts = [k for k in node_outputs if "downshift" in k.lower()]
    print(f"  cost-ceiling downshifts : {downshifts or 'none recorded'}")

    pkg = lesson.get("content") or node_outputs.get("package_builder") or {}
    segs = (pkg or {}).get("segments") or []
    if segs:
        words, providers = 0, {}
        for s in segs:
            narr = s.get("narration") or {}
            script = narr.get("script") or ""
            words += len(script.split())
            for a in (narr.get("audio_provider"),):
                if a:
                    providers[a] = providers.get(a, 0) + 1
        eff_wpm = WORDS_PER_MINUTE * SARVAM_PACE
        print(f"\n  SHIPPED PACKAGE: {len(segs)} segments, {words:,} narration words")
        print(
            f"  implied narration time: {words / eff_wpm:.1f} min "
            f"(at {eff_wpm:.1f} effective wpm)"
        )
        print(
            f"  metadata.estimated_duration_mins: "
            f"{_get(pkg, 'metadata', 'estimated_duration_mins', default='?')}"
        )
        print(f"  audio providers used: {providers or '(not recorded per segment)'}")
        quiz_total = sum(len(s.get("quiz") or []) for s in segs)
        print(f"  quiz questions shipped: {quiz_total}")

    # ── Q8: requested vs. deliverable ────────────────────────────────────────
    _h("Q8 — requested duration vs. what the source could support")
    if seat:
        target_narration = seat * NARRATION_SHARE
        eff_wpm = WORDS_PER_MINUTE * SARVAM_PACE
        need_chars = target_narration * eff_wpm * CHARS_PER_WORD
        print(f"  requested            : {seat} min seat time (tier {tier})")
        print(
            f"  narration target     : {target_narration:.2f} min "
            f"(= {NARRATION_SHARE:.0%} of seat time, under S5-4)"
        )
        print(f"  source chars needed  : ~{need_chars:,.0f}")
        if body_lengths:
            visible = sum(min(b, SECTION_BODY_MAX_CHARS) for b in body_lengths)
            print(f"  source chars visible : {visible:,}")
            print(
                f"  shortfall            : {max(0, need_chars - visible):,.0f} chars "
                f"({visible / need_chars:.0%} of what the target needs)"
            )
            ceiling = len(body_lengths) * SECTION_BODY_MAX_CHARS
            print(
                f"\n  HARD CEILING for this chapter's section count "
                f"({len(body_lengths)} x {SECTION_BODY_MAX_CHARS:,}) = {ceiling:,} chars "
                f"= {(ceiling / CHARS_PER_WORD) / eff_wpm:.1f} min of narration"
            )
    else:
        print(f"  tier {tier!r} not in the seat-time table — cannot compare.")

    _h("VERDICT")
    if truncations and body_lengths:
        n = len(body_lengths)
        print(
            f"  The per-section 6,000-char window truncated {len(truncations)} call(s)."
        )
        print(
            f"  With {n} section(s), the chapter can never exceed "
            f"{(n * SECTION_BODY_MAX_CHARS / CHARS_PER_WORD) / (WORDS_PER_MINUTE * SARVAM_PACE):.1f} "
            f"min of narration, whatever duration is requested."
        )
        print("  -> Root cause is the SOURCE WINDOW, bounded by the section count.")
    elif body_lengths and len(body_lengths) <= 3:
        print("  No truncation recorded, but the chapter yielded very few sections.")
        print("  -> Look at SECTION DETECTION first.")
    else:
        print("  Neither truncation nor a low section count explains it.")
        print("  -> Look at Q7: dropped/degraded segments, or generation-time failure.")


if __name__ == "__main__":
    main()
