"""
S4-33: Learner DNA profile quality review script.

Checks learner_dna profiles against 5 quality rules (no clinical language,
no raw scores, DPDP disclaimer present, encouraging tone, plain badge labels).

No app.* imports -- standalone script.

Usage (local fixture):
    python apps/api/scripts/review_dna_profiles.py \
        --fixture apps/api/tests/fixtures/sample_dna_profiles.json \
        --output dna_quality_report.csv

Usage (Supabase):
    export SUPABASE_URL=https://xxx.supabase.co
    export SUPABASE_SERVICE_ROLE_KEY=eyJ...
    python apps/api/scripts/review_dna_profiles.py \
        --output dna_quality_report.csv

Exit codes:
    0 -- all profiles pass all rules
    1 -- one or more rules FAIL on at least one profile
    2 -- argument error / missing input
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import sys
from typing import Any

_DEFAULT_LIMIT = 10_000
_DPDP_SUBSTRING = "DPDP Act 2023"
# The DPDP disclaimer sentence itself contains "clinical" ("not a clinical assessment").
# Strip from the sentence start so the no_clinical check targets only the profile body.
_DPDP_SENTENCE_START = "This profile is generated by AI"

# Patterns that indicate clinical language (case-insensitive)
_CLINICAL_TERMS = re.compile(
    r"\b(iq|eq|sq|clinical|diagnos\w*|disorder)\b", re.IGNORECASE
)

# Patterns that indicate raw numeric scores
_RAW_SCORE_PATTERNS = re.compile(
    r"(\d+/\d+|score:\s*\d)", re.IGNORECASE
)

# Words that indicate discouraging tone (case-insensitive)
_NEGATIVE_TONE_TERMS = re.compile(
    r"\b(struggle|fail\w*|weak|poor)\b", re.IGNORECASE
)

RULES = ["no_clinical", "no_raw_scores", "has_dpdp", "encouraging_tone", "plain_badge_labels"]


def _strip_dpdp(text: str) -> str:
    """Remove the required DPDP disclaimer sentence before pattern checks.

    The disclaimer sentence ("This profile is generated by AI and is not a
    clinical assessment. Data processed per DPDP Act 2023.") contains
    'clinical' by design, which would otherwise trigger a false positive on
    the no_clinical rule. Strip from the sentence start, not from "DPDP Act 2023",
    so the word 'clinical' in the boilerplate is excluded.
    """
    idx = text.find(_DPDP_SENTENCE_START)
    return text[:idx].rstrip() if idx != -1 else text


def check_no_clinical(profile_text: str) -> tuple[str, str]:
    body = _strip_dpdp(profile_text)
    match = _CLINICAL_TERMS.search(body)
    if match:
        return "FAIL", f"Clinical term found: '{match.group()}'"
    return "PASS", ""


def check_no_raw_scores(profile_text: str) -> tuple[str, str]:
    body = _strip_dpdp(profile_text)
    match = _RAW_SCORE_PATTERNS.search(body)
    if match:
        return "FAIL", f"Raw score pattern found: '{match.group()}'"
    return "PASS", ""


def check_has_dpdp(profile_text: str) -> tuple[str, str]:
    if _DPDP_SUBSTRING in profile_text:
        return "PASS", ""
    return "FAIL", f"Missing DPDP disclaimer (expected substring: '{_DPDP_SUBSTRING}')"


def check_encouraging_tone(profile_text: str) -> tuple[str, str]:
    body = _strip_dpdp(profile_text)
    match = _NEGATIVE_TONE_TERMS.search(body)
    if match:
        return "FAIL", f"Discouraging term found: '{match.group()}'"
    return "PASS", ""


def check_plain_badge_labels(badge_labels: list[str]) -> tuple[str, str]:
    for label in badge_labels:
        if ":" in label:
            return "FAIL", f"Badge label contains ':' — looks like a score format: '{label}'"
    return "PASS", ""


def review_profile(profile: dict[str, Any]) -> list[dict[str, Any]]:
    """Run all 5 rules on one profile. Returns list of result rows."""
    profile_id = profile.get("id", "")
    user_id = profile.get("user_id", "")
    text = profile.get("profile_text", "")
    badges: list[str] = profile.get("badge_labels") or []

    checks: list[tuple[str, tuple[str, str]]] = [
        ("no_clinical", check_no_clinical(text)),
        ("no_raw_scores", check_no_raw_scores(text)),
        ("has_dpdp", check_has_dpdp(text)),
        ("encouraging_tone", check_encouraging_tone(text)),
        ("plain_badge_labels", check_plain_badge_labels(badges)),
    ]

    return [
        {"profile_id": profile_id, "user_id": user_id, "rule": rule, "result": result, "detail": detail}
        for rule, (result, detail) in checks
    ]


def maybe_warn_signals_capped(*, signals_capped: bool, table: str, limit: int) -> None:
    """Print a warning when a Supabase query hit its .limit() boundary (SCALE-CONTRACT §2)."""
    if signals_capped:
        print(
            f"WARN: signals_capped=True for table '{table}' -- "
            f"query returned exactly {limit} rows (the limit). "
            "There may be more rows not included in this review. "
            "Re-run with --limit or a date filter.",
            flush=True,
        )


def load_from_fixture(path: str) -> list[dict[str, Any]]:
    """Load profiles from a local JSON fixture file."""
    try:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        if not isinstance(data, list):
            print(f"ERROR: fixture '{path}' must be a JSON array.", file=sys.stderr)
            sys.exit(2)
        return data
    except FileNotFoundError:
        print(f"ERROR: fixture file '{path}' not found.", file=sys.stderr)
        sys.exit(2)
    except json.JSONDecodeError as exc:
        print(f"ERROR: invalid JSON in '{path}': {exc}", file=sys.stderr)
        sys.exit(2)


def load_from_supabase(supabase_url: str, service_role_key: str, limit: int) -> list[dict[str, Any]]:
    """Load profiles from Supabase learner_dna table."""
    try:
        from supabase import create_client  # type: ignore[import-untyped]
    except ImportError:
        print("ERROR: supabase SDK not installed. Run: pip install supabase", file=sys.stderr)
        sys.exit(2)

    client = create_client(supabase_url, service_role_key)
    resp = (
        client.table("learner_dna")
        .select("id, user_id, profile_text, badge_labels, created_at")
        .limit(limit)
        .execute()
    )
    profiles = resp.data or []
    maybe_warn_signals_capped(signals_capped=len(profiles) == limit, table="learner_dna", limit=limit)
    return profiles


def write_report_csv(rows: list[dict[str, Any]], output: str) -> None:
    fieldnames = ["profile_id", "user_id", "rule", "result", "detail"]
    with open(output, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Review Learner DNA profiles against quality rules (S4-33).")
    parser.add_argument("--fixture", default=None, help="Path to local JSON fixture (bypasses Supabase)")
    parser.add_argument("--output", default="dna_quality_report.csv", help="Output CSV path")
    parser.add_argument(
        "--limit",
        type=int,
        default=_DEFAULT_LIMIT,
        help=f"Max rows from Supabase (default {_DEFAULT_LIMIT})",
    )
    args = parser.parse_args(argv)

    # Source selection: fixture > env vars > error
    if args.fixture:
        profiles = load_from_fixture(args.fixture)
    else:
        supabase_url = os.environ.get("SUPABASE_URL", "")
        service_role_key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY", "")
        if not supabase_url or not service_role_key:
            print(
                "ERROR: provide --fixture <path> or set SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY.",
                file=sys.stderr,
            )
            return 2
        profiles = load_from_supabase(supabase_url, service_role_key, args.limit)

    if not profiles:
        print("No profiles found to review.", file=sys.stderr)
        return 1

    print(f"Reviewing {len(profiles)} profiles against {len(RULES)} rules...")

    all_rows: list[dict[str, Any]] = []
    any_fail = False

    for profile in profiles:
        rows = review_profile(profile)
        all_rows.extend(rows)
        for row in rows:
            if row["result"] == "FAIL":
                any_fail = True
                print(f"  FAIL  profile={row['profile_id'][:12]} rule={row['rule']}: {row['detail']}")

    write_report_csv(all_rows, args.output)

    total_checks = len(all_rows)
    fail_count = sum(1 for r in all_rows if r["result"] == "FAIL")
    pass_count = total_checks - fail_count
    print(f"\nResult: {pass_count}/{total_checks} checks passed. Report: {args.output}")

    return 1 if any_fail else 0


if __name__ == "__main__":
    sys.exit(main())
