-- D72: Brand rename "TransformED" → "HIE" in learner_dna.profile_text.
--
-- DPDP_DISCLAIMER and ONBOARDING_PROFILE_SYSTEM_PROMPT in prompts.py are fixed
-- in code (Story 3-54). This migration backfills existing rows where GPT-4o-mini
-- already echoed the old brand into profile_text at onboarding time.
--
-- Scope: per-deployment across all learner_dna rows (one row per registered user).
-- Expected row count at Sprint 3 launch: < 100 rows (test users only).
-- At that scale the full sequential scan on profile_text completes in < 1ms and
-- holds RowExclusiveLock for a negligible window. At 10,000+ users a maintenance
-- window would be advisable before running this migration.
--
-- Case sensitivity: REPLACE() is exact-case. All existing profile_text values were
-- generated by GPT-4o-mini from ONBOARDING_PROFILE_SYSTEM_PROMPT, which reliably
-- produces "TransformED" capitalisation (capital T, capital ED). Non-standard
-- capitalisation variants are not expected in production data.
--
-- Uses REPLACE() which is non-destructive: rows without "TransformED" are
-- unchanged (LIKE guard prevents a full-table write for no-op rows).
-- Safe to run multiple times (idempotent: REPLACE on a string that no longer
-- contains the target is a no-op).

UPDATE learner_dna
SET    profile_text = REPLACE(profile_text, 'TransformED', 'HIE')
WHERE  profile_text LIKE '%TransformED%';
